# Generated by Django 6.0.4 on 2026-04-15 16:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_id', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=500)),
                ('poster_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('watching', 'Watching'), ('completed', 'Completed'), ('dropped', 'Dropped'), ('plan_to_watch', 'Plan to Watch')], default='plan_to_watch', max_length=20)),
                ('share_id', models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True)),
                ('current_episode', models.IntegerField(default=0)),
                ('total_episodes', models.IntegerField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('genres', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'mail_id')},
            },
        ),
        migrations.CreateModel(
            name='EpisodeNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_number', models.IntegerField()),
                ('timestamp', models.CharField(blank=True, max_length=50)),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episode_notes', to='Anime.animeentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
