# Generated by Django 6.0.4 on 2026-04-24 10:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Anime', '0002_watchlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='animeentry',
            old_name='mail_id',
            new_name='mal_id',
        ),
        migrations.AlterUniqueTogether(
            name='animeentry',
            unique_together={('user', 'mal_id')},
        ),
    ]
