# Generated by Django 6.0.4 on 2026-04-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anime', '0003_rename_mail_id_animeentry_mal_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlog',
            name='episode',
            field=models.IntegerField(default=1),
        ),
    ]
