# Generated by Django 6.0.4 on 2026-08-03 12:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anime', '0004_watchlog_episode'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodenote',
            name='share_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='episodenote',
            name='timestamp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
