# Generated by Django 6.0.4 on 2026-08-03 13:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anime', '0005_episodenote_share_id_alter_episodenote_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodenote',
            name='share_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
