# Generated by Django 6.0.4 on 2026-08-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anime', '0008_supportticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportticket',
            name='is_resolved',
        ),
        migrations.AddField(
            model_name='supportticket',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='in_progress', max_length=20),
        ),
    ]
