# Generated by Django 6.0.4 on 2026-08-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anime', '0010_ticketreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketreply',
            name='admin_response',
            field=models.TextField(blank=True, help_text='Support response from admin', null=True),
        ),
    ]
