# Generated by Django 6.0.4 on 2026-08-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anime', '0011_ticketreply_admin_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketreply',
            name='admin_response',
        ),
        migrations.AddField(
            model_name='supportticket',
            name='admin_response',
            field=models.TextField(blank=True, help_text='Support response from admin', null=True),
        ),
    ]
